In [5]:
from selenium import webdriver 
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
from selenium.webdriver.common.keys import Keys
driver = webdriver.Chrome('C:/chromedriver.exe')
driver.get('https://www.seoul.go.kr/coronaV/coronaStatus.do#status_page_top')
import time

In [6]:
a = []
b = []
c = []
d = []
e = []
f = []
g =[]

for n in range(1,18): ##여기 30은 그 다음페이지 넘어가는 거라서 40개씩 보는걸로 해놨기 때문에 만약 검사결과가    
# get titles, address(url)
    print(n)
    res = driver.page_source
    soup = BeautifulSoup(res, "html.parser")
    contents = soup.select('#DataTables_Table_0 > tbody > tr')[0:100]
    for i in range(0,len(contents)):
        content = contents[i]
        a.append(content.select_one('th').text)
        b.append(content.select_one('td:nth-child(2)').text)
        c.append(content.select_one('td:nth-child(3)').text)
        d.append(content.select_one('td:nth-child(4)').text)
        e.append(content.select_one('td:nth-child(5)').text)
        f.append(content.select_one('td:nth-child(6)').text)
        g.append(content.select_one('td:nth-child(7)').text)
            
    page_bar = driver.find_elements_by_css_selector('a#DataTables_Table_0_next.paginate_button.next')
    page_bar[0].click()
    time.sleep(2)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16

AttributeError: 'NoneType' object has no attribute 'text'

In [7]:
data = {'연번':a, '환자':b, '확진일자': c, '거주지' : d,
       '여행력': e,'접촉력':f, '조치사항':g}
df = pd.DataFrame(data)
df.describe()

          연번     환자   확진일자   거주지   여행력       접촉력       조치사항
count   1526   1526   1526  1526  1526      1526       1526
unique  1526   1525    153    60    63       147         82
top     1293  13854  3.10.   관악구     -  해외 접촉 추정  서울의료원(퇴원)
freq       1      2     46   137  1193       307        407

In [8]:
df

        연번     환자   확진일자   거주지     여행력         접촉력         조치사항
0     1526  13926  7.22.   송파구       -    송파구 교회관련        서울의료원
1     1525  13925  7.22.   송파구       -    송파구 교회관련        서울의료원
2     1524  13924  7.22.   강남구       -  타시도 확진자 접촉        보라매병원
3     1523  13921  7.22.  동대문구       -        확인 중       삼육서울병원
4     1522  13917  7.22.   강남구       -  타시도 확진자 접촉        원자력병원
...    ...    ...    ...   ...     ...         ...          ...
1521     5      9  1.31.   성북구       -       #5 접촉    서울의료원(퇴원)
1522     4      7  1.30.   마포구  중국 우한시       해외 접촉    서울의료원(퇴원)
1523     3      6  1.30.   종로구       -       #3 접촉  서울대학교병원(퇴원)
1524     2      5  1.30.   중랑구  중국 우한시       해외 접촉    서울의료원(퇴원)
1525     1      2  1.24.   강서구  중국 우한시       해외 접촉  국립중앙의료원(퇴원)

[1526 rows x 7 columns]

In [9]:
df.to_excel('서울 확진자 정보.xlsx')